--------------------------------------------------------
-- Archivo creado  - martes-octubre-31-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPRESAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."EMPRESAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ESTADOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."ESTADOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."MENUS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MUNICIPIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."MUNICIPIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PARROQUIAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."PARROQUIAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PERSONAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."PERSONAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROFESIONES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."PROFESIONES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREVISION"."ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table EMPRESAS
--------------------------------------------------------

  CREATE TABLE "PREVISION"."EMPRESAS" 
   (	"CD_EMPRESA" NUMBER, 
	"CD_PERSONA" NUMBER, 
	"IN_ASOPROINFU" NUMBER, 
	"CD_ASOPROINFU" NUMBER, 
	"FE_REGISTRO" DATE, 
	"ST_EMPRESA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table ESTADOS
--------------------------------------------------------

  CREATE TABLE "PREVISION"."ESTADOS" 
   (	"CD_ESTADO" NUMBER, 
	"DE_ESTADO" VARCHAR2(200 BYTE), 
	"ST_ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table MENUROL
--------------------------------------------------------

  CREATE TABLE "PREVISION"."MENUROL" 
   (	"CD_MENU" NUMBER, 
	"CD_ROL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table MENUS
--------------------------------------------------------

  CREATE TABLE "PREVISION"."MENUS" 
   (	"CD_MENU" NUMBER, 
	"CD_MENU_PADRE" NUMBER, 
	"DE_MENU" VARCHAR2(100 BYTE), 
	"TP_MENU" NUMBER, 
	"DE_ICONO_MENU" VARCHAR2(100 BYTE), 
	"CD_ORDEN_MENU" NUMBER, 
	"DE_ENLACE_MENU" VARCHAR2(500 BYTE), 
	"ST_MENU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table MUNICIPIOS
--------------------------------------------------------

  CREATE TABLE "PREVISION"."MUNICIPIOS" 
   (	"CD_MUNICIPIO" NUMBER, 
	"DE_MUNICIPIO" VARCHAR2(200 BYTE), 
	"CD_ESTADO" NUMBER, 
	"ST_MUNICIPIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table NUMERACIONCONTRATO
--------------------------------------------------------

  CREATE TABLE "PREVISION"."NUMERACIONCONTRATO" 
   (	"CD_PRODUCTO" NUMBER, 
	"CD_NUMERACION_CONTRATO" NUMBER, 
	"CD_EMPRESA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table PARROQUIAS
--------------------------------------------------------

  CREATE TABLE "PREVISION"."PARROQUIAS" 
   (	"CD_PARROQUIA" NUMBER, 
	"DE_PARROQUIA" VARCHAR2(200 BYTE), 
	"CD_MUNICIPIO" NUMBER, 
	"ST_PARRROQUIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table PERSONACORREO
--------------------------------------------------------

  CREATE TABLE "PREVISION"."PERSONACORREO" 
   (	"CD_PERSONA" NUMBER, 
	"DE_CORREO" VARCHAR2(100 BYTE), 
	"ST_CORREO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table PERSONADIRECCION
--------------------------------------------------------

  CREATE TABLE "PREVISION"."PERSONADIRECCION" 
   (	"CD_PERSONA" NUMBER, 
	"CD_ESTADO" NUMBER, 
	"CD_MUNICIPIO" NUMBER, 
	"CD_PARROQUIA" NUMBER, 
	"DE_DIRECCION" VARCHAR2(500 BYTE), 
	"TP_PRIORIDAD" NUMBER, 
	"ST_DIRECCION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table PERSONAS
--------------------------------------------------------

  CREATE TABLE "PREVISION"."PERSONAS" 
   (	"CD_PERSONA" NUMBER, 
	"NM_PERSONA1" VARCHAR2(100 BYTE), 
	"NM_PERSONA2" VARCHAR2(100 BYTE), 
	"AP_PERSONA1" VARCHAR2(100 BYTE), 
	"AP_PERSONA2" VARCHAR2(100 BYTE), 
	"TP_DOCUMENTO" VARCHAR2(4 BYTE), 
	"NU_DOCUMENTO" VARCHAR2(100 BYTE), 
	"CD_SEXO" VARCHAR2(4 BYTE), 
	"CD_PROFESION" NUMBER, 
	"FE_REGISTRO" DATE, 
	"FE_FALLECIMIENTO" DATE, 
	"NM_COMPLETO" VARCHAR2(200 BYTE), 
	"ST_PERSONA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table PERSONATELEFONO
--------------------------------------------------------

  CREATE TABLE "PREVISION"."PERSONATELEFONO" 
   (	"CD_PERSONA" NUMBER, 
	"CD_AREA" NUMBER, 
	"NU_TELEFONO" NUMBER, 
	"TP_TELEFONO" NUMBER, 
	"TP_PRIORIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table PROFESIONES
--------------------------------------------------------

  CREATE TABLE "PREVISION"."PROFESIONES" 
   (	"CD_PROFESION" NUMBER, 
	"DE_PROFESION" VARCHAR2(200 BYTE), 
	"ST_PROFESION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "PREVISION"."ROLES" 
   (	"CD_ROL" NUMBER, 
	"DE_ROL" VARCHAR2(100 BYTE), 
	"ST_ROL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table SEXOS
--------------------------------------------------------

  CREATE TABLE "PREVISION"."SEXOS" 
   (	"CD_SEXO" VARCHAR2(4 BYTE), 
	"DE_SEXO" VARCHAR2(100 BYTE), 
	"ST_SEXO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table TIPODOCUMENTO
--------------------------------------------------------

  CREATE TABLE "PREVISION"."TIPODOCUMENTO" 
   (	"CD_TIPO_DOCUMENTO" VARCHAR2(4 BYTE), 
	"DE_TIPO_DOCUMENTO" VARCHAR2(100 BYTE), 
	"ST_TIPO_DOCUMENTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table USUARIOROL
--------------------------------------------------------

  CREATE TABLE "PREVISION"."USUARIOROL" 
   (	"CD_USUARIO" VARCHAR2(100 BYTE), 
	"CD_ROL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PREVISION"."USUARIOS" 
   (	"CD_USUARIO" VARCHAR2(100 BYTE), 
	"CD_PERSONA" NUMBER, 
	"FE_REGISTRO" DATE, 
	"DE_CLAVE" VARCHAR2(512 BYTE), 
	"ST_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
REM INSERTING into PREVISION.EMPRESAS
SET DEFINE OFF;
REM INSERTING into PREVISION.ESTADOS
SET DEFINE OFF;
REM INSERTING into PREVISION.MENUROL
SET DEFINE OFF;
Insert into PREVISION.MENUROL (CD_MENU,CD_ROL) values ('2','1');
Insert into PREVISION.MENUROL (CD_MENU,CD_ROL) values ('3','1');
Insert into PREVISION.MENUROL (CD_MENU,CD_ROL) values ('5','1');
REM INSERTING into PREVISION.MENUS
SET DEFINE OFF;
Insert into PREVISION.MENUS (CD_MENU,CD_MENU_PADRE,DE_MENU,TP_MENU,DE_ICONO_MENU,CD_ORDEN_MENU,DE_ENLACE_MENU,ST_MENU) values ('1',null,'Menu Padre','1','typcn-briefcase menu-icon','1',null,'1');
Insert into PREVISION.MENUS (CD_MENU,CD_MENU_PADRE,DE_MENU,TP_MENU,DE_ICONO_MENU,CD_ORDEN_MENU,DE_ENLACE_MENU,ST_MENU) values ('2','1','Menu Hijo#1','2',null,'1','/prevision.prueba','1');
Insert into PREVISION.MENUS (CD_MENU,CD_MENU_PADRE,DE_MENU,TP_MENU,DE_ICONO_MENU,CD_ORDEN_MENU,DE_ENLACE_MENU,ST_MENU) values ('3','1','Menu Hijo#2','2',null,'2','/prevision.prueba1','1');
Insert into PREVISION.MENUS (CD_MENU,CD_MENU_PADRE,DE_MENU,TP_MENU,DE_ICONO_MENU,CD_ORDEN_MENU,DE_ENLACE_MENU,ST_MENU) values ('4',null,'Menu Padre #2','1','typcn-briefcase menu-icon','1',null,'1');
Insert into PREVISION.MENUS (CD_MENU,CD_MENU_PADRE,DE_MENU,TP_MENU,DE_ICONO_MENU,CD_ORDEN_MENU,DE_ENLACE_MENU,ST_MENU) values ('5','4','Menu Hijo#1','2',null,'2','/prevision.prueba1','1');
REM INSERTING into PREVISION.MUNICIPIOS
SET DEFINE OFF;
REM INSERTING into PREVISION.NUMERACIONCONTRATO
SET DEFINE OFF;
REM INSERTING into PREVISION.PARROQUIAS
SET DEFINE OFF;
REM INSERTING into PREVISION.PERSONACORREO
SET DEFINE OFF;
REM INSERTING into PREVISION.PERSONADIRECCION
SET DEFINE OFF;
REM INSERTING into PREVISION.PERSONAS
SET DEFINE OFF;
Insert into PREVISION.PERSONAS (CD_PERSONA,NM_PERSONA1,NM_PERSONA2,AP_PERSONA1,AP_PERSONA2,TP_DOCUMENTO,NU_DOCUMENTO,CD_SEXO,CD_PROFESION,FE_REGISTRO,FE_FALLECIMIENTO,NM_COMPLETO,ST_PERSONA) values ('1','Yorman','Yuan','Medina','Duque','V','23695018','M','1',to_date('30/10/23','DD/MM/RR'),null,'Yorman Medina','1');
REM INSERTING into PREVISION.PERSONATELEFONO
SET DEFINE OFF;
REM INSERTING into PREVISION.PROFESIONES
SET DEFINE OFF;
Insert into PREVISION.PROFESIONES (CD_PROFESION,DE_PROFESION,ST_PROFESION) values ('1','Contador','1');
REM INSERTING into PREVISION.ROLES
SET DEFINE OFF;
Insert into PREVISION.ROLES (CD_ROL,DE_ROL,ST_ROL) values ('1','admin','1');
REM INSERTING into PREVISION.SEXOS
SET DEFINE OFF;
Insert into PREVISION.SEXOS (CD_SEXO,DE_SEXO,ST_SEXO) values ('M','Masculino','1');
Insert into PREVISION.SEXOS (CD_SEXO,DE_SEXO,ST_SEXO) values ('F','Femenino','1');
REM INSERTING into PREVISION.TIPODOCUMENTO
SET DEFINE OFF;
Insert into PREVISION.TIPODOCUMENTO (CD_TIPO_DOCUMENTO,DE_TIPO_DOCUMENTO,ST_TIPO_DOCUMENTO) values ('V','Venezolano','1');
Insert into PREVISION.TIPODOCUMENTO (CD_TIPO_DOCUMENTO,DE_TIPO_DOCUMENTO,ST_TIPO_DOCUMENTO) values ('E','Extranjero','1');
REM INSERTING into PREVISION.USUARIOROL
SET DEFINE OFF;
Insert into PREVISION.USUARIOROL (CD_USUARIO,CD_ROL) values ('ymedina','1');
REM INSERTING into PREVISION.USUARIOS
SET DEFINE OFF;
Insert into PREVISION.USUARIOS (CD_USUARIO,CD_PERSONA,FE_REGISTRO,DE_CLAVE,ST_USUARIO) values ('ymedina','1',to_date('30/10/23','DD/MM/RR'),'70d51ef2a71c03dd606d6a40db4eac14f9b363d63f080046389f87d49110faf1','1');
--------------------------------------------------------
--  DDL for Index ROLES_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."ROLES_UK1" ON "PREVISION"."ROLES" ("DE_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index EMPRESAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."EMPRESAS_PK" ON "PREVISION"."EMPRESAS" ("CD_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index MUNICIPIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."MUNICIPIOS_PK" ON "PREVISION"."MUNICIPIOS" ("CD_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index TIPODOCUMENTO_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."TIPODOCUMENTO_UK2" ON "PREVISION"."TIPODOCUMENTO" ("DE_TIPO_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index MUNICIPIOS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."MUNICIPIOS_UK1" ON "PREVISION"."MUNICIPIOS" ("DE_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index SEXOS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."SEXOS_UK1" ON "PREVISION"."SEXOS" ("DE_SEXO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index SEXOS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."SEXOS_PK1" ON "PREVISION"."SEXOS" ("CD_SEXO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index ESTADOS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."ESTADOS_UK1" ON "PREVISION"."ESTADOS" ("DE_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index TIPODOCUMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."TIPODOCUMENTO_PK" ON "PREVISION"."TIPODOCUMENTO" ("CD_TIPO_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index EMPRESAS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."EMPRESAS_UK1" ON "PREVISION"."EMPRESAS" ("CD_ASOPROINFU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."USUARIOS_PK" ON "PREVISION"."USUARIOS" ("CD_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index PERSONAS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."PERSONAS_UK1" ON "PREVISION"."PERSONAS" ("NU_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index PERSONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."PERSONAS_PK" ON "PREVISION"."PERSONAS" ("CD_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index PROFESIONES_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."PROFESIONES_UK1" ON "PREVISION"."PROFESIONES" ("DE_PROFESION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index MENUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."MENUS_PK" ON "PREVISION"."MENUS" ("CD_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index PARROQUIAS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."PARROQUIAS_UK1" ON "PREVISION"."PARROQUIAS" ("DE_PARROQUIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index PROFESIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."PROFESIONES_PK" ON "PREVISION"."PROFESIONES" ("CD_PROFESION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index PARROQUIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."PARROQUIAS_PK" ON "PREVISION"."PARROQUIAS" ("CD_PARROQUIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index ESTADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."ESTADOS_PK" ON "PREVISION"."ESTADOS" ("CD_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVISION"."ROLES_PK" ON "PREVISION"."ROLES" ("CD_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  Constraints for Table EMPRESAS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."EMPRESAS" ADD CONSTRAINT "EMPRESAS_UK1" UNIQUE ("CD_ASOPROINFU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."EMPRESAS" ADD CONSTRAINT "EMPRESAS_PK" PRIMARY KEY ("CD_EMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."EMPRESAS" MODIFY ("CD_EMPRESA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPODOCUMENTO
--------------------------------------------------------

  ALTER TABLE "PREVISION"."TIPODOCUMENTO" ADD CONSTRAINT "TIPODOCUMENTO_UK2" UNIQUE ("DE_TIPO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."TIPODOCUMENTO" ADD CONSTRAINT "TIPODOCUMENTO_PK" PRIMARY KEY ("CD_TIPO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."TIPODOCUMENTO" MODIFY ("CD_TIPO_DOCUMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUNICIPIOS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."MUNICIPIOS" ADD CONSTRAINT "MUNICIPIOS_UK1" UNIQUE ("DE_MUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."MUNICIPIOS" ADD CONSTRAINT "MUNICIPIOS_PK" PRIMARY KEY ("CD_MUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."MUNICIPIOS" MODIFY ("CD_MUNICIPIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARROQUIAS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."PARROQUIAS" ADD CONSTRAINT "PARROQUIAS_UK1" UNIQUE ("DE_PARROQUIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."PARROQUIAS" ADD CONSTRAINT "PARROQUIAS_PK" PRIMARY KEY ("CD_PARROQUIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."PARROQUIAS" MODIFY ("CD_PARROQUIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."PERSONAS" ADD CONSTRAINT "PERSONAS_UK1" UNIQUE ("NU_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."PERSONAS" ADD CONSTRAINT "PERSONAS_PK" PRIMARY KEY ("CD_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."PERSONAS" MODIFY ("CD_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENUS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."MENUS" ADD CONSTRAINT "MENUS_PK" PRIMARY KEY ("CD_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."MENUS" MODIFY ("CD_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("CD_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."USUARIOS" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFESIONES
--------------------------------------------------------

  ALTER TABLE "PREVISION"."PROFESIONES" ADD CONSTRAINT "PROFESIONES_UK1" UNIQUE ("DE_PROFESION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."PROFESIONES" ADD CONSTRAINT "PROFESIONES_PK" PRIMARY KEY ("CD_PROFESION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."PROFESIONES" MODIFY ("CD_PROFESION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "PREVISION"."ROLES" ADD CONSTRAINT "ROLES_UK1" UNIQUE ("DE_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("CD_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADOS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."ESTADOS" ADD CONSTRAINT "ESTADOS_UK1" UNIQUE ("DE_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."ESTADOS" ADD CONSTRAINT "ESTADOS_PK" PRIMARY KEY ("CD_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."ESTADOS" MODIFY ("CD_ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOROL
--------------------------------------------------------

  ALTER TABLE "PREVISION"."USUARIOROL" MODIFY ("CD_ROL" NOT NULL ENABLE);
  ALTER TABLE "PREVISION"."USUARIOROL" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEXOS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."SEXOS" ADD CONSTRAINT "SEXOS_UK1" UNIQUE ("DE_SEXO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."SEXOS" ADD CONSTRAINT "SEXOS_PK1" PRIMARY KEY ("CD_SEXO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "PREVISION"."SEXOS" MODIFY ("CD_SEXO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NUMERACIONCONTRATO
--------------------------------------------------------

  ALTER TABLE "PREVISION"."NUMERACIONCONTRATO" MODIFY ("CD_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "PREVISION"."NUMERACIONCONTRATO" MODIFY ("CD_NUMERACION_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "PREVISION"."NUMERACIONCONTRATO" MODIFY ("CD_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPRESAS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."EMPRESAS" ADD CONSTRAINT "EMPRESAS_FK" FOREIGN KEY ("CD_PERSONA")
	  REFERENCES "PREVISION"."PERSONAS" ("CD_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENUROL
--------------------------------------------------------

  ALTER TABLE "PREVISION"."MENUROL" ADD CONSTRAINT "MENUROL_FK" FOREIGN KEY ("CD_MENU")
	  REFERENCES "PREVISION"."MENUS" ("CD_MENU") ENABLE;
  ALTER TABLE "PREVISION"."MENUROL" ADD CONSTRAINT "MENUROL_FK2" FOREIGN KEY ("CD_ROL")
	  REFERENCES "PREVISION"."ROLES" ("CD_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNICIPIOS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."MUNICIPIOS" ADD CONSTRAINT "MUNICIPIOS_FK" FOREIGN KEY ("CD_ESTADO")
	  REFERENCES "PREVISION"."ESTADOS" ("CD_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARROQUIAS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."PARROQUIAS" ADD CONSTRAINT "PARROQUIAS_FK" FOREIGN KEY ("CD_MUNICIPIO")
	  REFERENCES "PREVISION"."MUNICIPIOS" ("CD_MUNICIPIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONACORREO
--------------------------------------------------------

  ALTER TABLE "PREVISION"."PERSONACORREO" ADD CONSTRAINT "PERSONACORREO_FK" FOREIGN KEY ("CD_PERSONA")
	  REFERENCES "PREVISION"."PERSONAS" ("CD_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONADIRECCION
--------------------------------------------------------

  ALTER TABLE "PREVISION"."PERSONADIRECCION" ADD CONSTRAINT "PERSONADIRECCION_FK" FOREIGN KEY ("CD_PERSONA")
	  REFERENCES "PREVISION"."PERSONAS" ("CD_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."PERSONAS" ADD CONSTRAINT "PERSONAS_FK" FOREIGN KEY ("CD_SEXO")
	  REFERENCES "PREVISION"."SEXOS" ("CD_SEXO") ENABLE;
  ALTER TABLE "PREVISION"."PERSONAS" ADD CONSTRAINT "PERSONAS_FK2" FOREIGN KEY ("CD_PROFESION")
	  REFERENCES "PREVISION"."PROFESIONES" ("CD_PROFESION") ENABLE;
  ALTER TABLE "PREVISION"."PERSONAS" ADD CONSTRAINT "PERSONAS_FK3" FOREIGN KEY ("TP_DOCUMENTO")
	  REFERENCES "PREVISION"."TIPODOCUMENTO" ("CD_TIPO_DOCUMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONATELEFONO
--------------------------------------------------------

  ALTER TABLE "PREVISION"."PERSONATELEFONO" ADD CONSTRAINT "PERSONATELEFONO_FK" FOREIGN KEY ("CD_PERSONA")
	  REFERENCES "PREVISION"."PERSONAS" ("CD_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOROL
--------------------------------------------------------

  ALTER TABLE "PREVISION"."USUARIOROL" ADD CONSTRAINT "USUARIOROL_FK" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "PREVISION"."USUARIOS" ("CD_USUARIO") ENABLE;
  ALTER TABLE "PREVISION"."USUARIOROL" ADD CONSTRAINT "USUARIOROL_FK2" FOREIGN KEY ("CD_ROL")
	  REFERENCES "PREVISION"."ROLES" ("CD_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PREVISION"."USUARIOS" ADD CONSTRAINT "USUARIOS_FK" FOREIGN KEY ("CD_PERSONA")
	  REFERENCES "PREVISION"."PERSONAS" ("CD_PERSONA") ENABLE;
