
CREATE TABLE PREVISION.TEMPORALCOLECTIVO
(
  NOMBRE1                    VARCHAR2(30 BYTE),
  APELLIDO1                  VARCHAR2(30 BYTE),
  TP_DOCUMENTO_TITULAR       VARCHAR2(1 BYTE),
  NU_DOCUMENTO_TITULAR       VARCHAR2(20 BYTE),
  TP_DOCUMENTO_BENEFICIARIO  VARCHAR2(1 BYTE),
  NU_DOCUMENTO_BENEFICIARIO  VARCHAR2(20 BYTE),
  FE_NACIMIENTO              DATE,
  CD_SEXO                    VARCHAR2(1 BYTE),
  CD_PARENTESCO              NUMBER,
  MT_SUMA                    NUMBER,
  MT_PRIMA                   NUMBER,
  ERROR                      VARCHAR2(1000 BYTE),
  NU_LINEA                   NUMBER,
  NU_TEMPORAL                NUMBER,
  MT_PRIMA_PLAN              NUMBER,
  ES_ADICIONAL               VARCHAR2(2 BYTE)
)
CREATE TABLE PREVISION.TEMPORALCOLECTIVOPRODUCTO
(
  CD_PRODUCTO           NUMBER,
  CD_COBERTURA          NUMBER,
  CD_GRUPO_FAMILIAR     NUMBER,
  CD_COBERTURA_DETALLE  NUMBER,
  TP_CALCULO            NUMBER,
  CD_PLAN_PAGO          NUMBER,
  NU_TEMPORAL           NUMBER
)

CREATE SEQUENCE PREVISION.TEMPORALCOLECTIVO_SEQ
  START WITH 61
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;